
# Site settings

url: "https://arbianchi.github.io"

baseurl: 

google-tracking-id: ""

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Adina Bianchi"
title: "{ Adina Bianchi }"
description: "Adina Bianchi - Softward Developer"
keywords: "adina, bianchi, arbianchi"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: 

background-img: "../img/blueridge2.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 3000
lines: # You can add HTML Tags in the Text
  - text: "Software Developer"
  - text: "Développeur Logiciel"

me-img: "/img/self.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

############
# Timeline #
############

events:
  - image: "/img/timeline/logo-vt.png"
    date: "January 2017 - Today"
    description: "Développeur à Voicethread"
  - image: "/img/timeline/tiy.png"
    date: "Summer 2017"
    description: "Iron Yard Backend Engineering Immersive"
  - image: "/img/timeline/yale.png"
    date: "2014-2016"
    description: "Lab Manager of Cognitive Neuroscience Lab"
    
french_events:
  - image: "/img/timeline/logo-vt.png"
    date: "Janvier 2017 - Aujourd'hui"
    description: "Développeur at Voicethread"
  - image: "/img/timeline/tiy.png"
    date: "Été 2017"
    description: "Iron Yard Ruby on Rails Cours Immersif"
  - image: "/img/timeline/yale.png"
    date: "2014-2016"
    description: "Coordinateur du lab neuroscience cognitive"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "acuriousloop@gmail.com"


##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/arbianchi"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

############
# Pages #
############

pages_list:
  About: 'about'
  Timeline: 'timeline'
  Contact: 'contact'

french_pages_list:
  À Propos: 'apropos'
  Chronologie: 'chronologie'
  Contacte: 'contacte'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
